### ISSUE TITLE
Compiler issue with ionic-native

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-native#1060]
I have tried to test `ionic-native@3.0.0` with following plugins: 

```json 
"@ionic-native/file": "3.0.0",
"@ionic-native/network": "3.0.0",
"@ionic-native/onesignal": "3.0.0",
"@ionic-native/socialsharing": "3.0.0",
"@ionic-native/splashscreen": "3.0.0",
"@ionic-native/statusbar": "3.0.0",
"@ionic-native/themeable-browser": "3.0.0",
```

`ionic serve` works fine, but when running `ionic build` or `ionic-run` the AOT compiler thorwse the following error:

```
[19:40:32]  ngc started ... 
Failed on type {"filePath":"/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/template_parser/template_parser.d.ts","name":"TemplateParser","members":[]} with error Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 15:13 in the original .ts file), resolving symbol UNINITIALIZED in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/change_detection/change_detection_util.d.ts, resolving symbol ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core_private_export.d.ts, resolving symbol ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core.d.ts, resolving symbol ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/index.d.ts, resolving symbol Console in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/private_import_core.d.ts, resolving symbol TemplateParser in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/template_parser/template_parser.d.ts
[19:40:44]  build prod failed: Error encountered resolving symbol values statically. Function calls are not supported. 
            Consider replacing the function or lambda with a reference to an exported function (position 15:13 in the 
            original .ts file), resolving symbol UNINITIALIZED in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/change_detection/change_detection_util.d.ts,
            resolving symbol ___core_private__ in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core_private_export.d.ts, 
            resolving symbol ___core_private__ in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core.d.ts, resolving symbol 
            ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/index.d.ts, 
            resolving symbol Console in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/private_import_core.d.ts, 
            resolving symbol TemplateParser in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/template_parser/template_parser.d.ts
[19:40:44]  ionic-app-script task: "build" 
[19:40:44]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
            replacing the function or lambda with a reference to an exported function (position 15:13 in the original 
            .ts file), resolving symbol UNINITIALIZED in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/change_detection/change_detection_util.d.ts,
            resolving symbol ___core_private__ in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core_private_export.d.ts, 
            resolving symbol ___core_private__ in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core.d.ts, resolving symbol 
            ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/index.d.ts, 
            resolving symbol Console in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/private_import_core.d.ts, 
            resolving symbol TemplateParser in 
            /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/template_parser/template_parser.d.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 15:13 in the original .ts file), resolving symbol UNINITIALIZED in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/change_detection/change_detection_util.d.ts, resolving symbol ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core_private_export.d.ts, resolving symbol ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/src/core.d.ts, resolving symbol ___core_private__ in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/core/index.d.ts, resolving symbol Console in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/private_import_core.d.ts, resolving symbol TemplateParser in /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@angular/compiler/src/template_parser/template_parser.d.ts
    at positionalError (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:25956:39)
    at simplifyInContext (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:25793:31)
    at StaticReflector.simplify (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:25807:17)
    at StaticReflector.parameters (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:25361:69)
    at CompileMetadataResolver._getDependenciesMetadata (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:18618:75)
    at CompileMetadataResolver._getTypeMetadata (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:18545:30)
    at CompileMetadataResolver.getInjectableSummary (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:18520:77)
    at /Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:24749:387
    at Array.map (native)
    at AotCompiler._createSummary (/Users/attila/budacode/PLACEHOLDER-mobile/node_modules/@ionic/app-scripts/node_modules/@angular/compiler/bundles/compiler.umd.js:24749:335)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "build" "--device"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! PLACEHOLDER-mobile@ build: `node ./config/bootstrap.js && ionic-app-scripts build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PLACEHOLDER-mobile@ build script 'node ./config/bootstrap.js && ionic-app-scripts build --prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PLACEHOLDER-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./config/bootstrap.js && ionic-app-scripts build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PLACEHOLDER-mobile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PLACEHOLDER-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/attila/budacode/PLACEHOLDER-mobile/npm-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "ionic:build" "--" "--device"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! PLACEHOLDER-mobile@ ionic:build: `npm run build "--device"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PLACEHOLDER-mobile@ ionic:build script 'npm run build "--device"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PLACEHOLDER-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build "--device"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PLACEHOLDER-mobile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PLACEHOLDER-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/attila/budacode/PLACEHOLDER-mobile/npm-debug.log

```

**Comment by mlynch** [comment]
Thanks, we need to get ngc/AoT in there, haven't gotten to that yet
