### ISSUE TITLE
[3.1.0-rc.3] No provider for Globalization 

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic-native#1178]
After updating to 3.1.0-rc.3 I needed to change Ionic Native usage to use dependency injection, which is great. However, I'm getting an error for the globalization plugin

```
Unhandled Promise rejection: No provider for Globalization! ; Zone: <root> ; Task: Promise.then ; Value: NoProviderError {_nativeError: Error: No provider for Globalization!
    at v (http://localhost:8100/build/polyfills.js:3:4864)
   …, keys: Array[1], injectors: Array[1]} Error: DI Error
    at v (http://localhost:8100/build/polyfills.js:3:4864)
    at NoProviderError.BaseError [as constructor] (http://localhost:810
```

Here's my service code:

```ts
import { Injectable } from '@angular/core';

import { Platform } from 'ionic-angular';
import { Globalization } from '@ionic-native/globalization';

@Injectable()
export class I18nService {

	public constructor(
		protected _platform: Platform,
		protected _globalization: Globalization
	) {

	}

	/**
	 * Returns a supported ISO 639-1 alpha-2 language code (e.g. en)
	 */
	public getPreferredLanguage(): Promise<string> {
		return this._getLanguageIdentifierTag()
			.then(val => val.slice(0, 2));
	}

	/**
	 * Returns ISO 3166-1 alpha-2 country code (e.g. DK)
	 */
	public getPreferredCountry(): Promise<string> {
		return this._getLanguageIdentifierTag()
			.then(val => val.slice(3, 5));
	}

	/**
	 * Returns BCP-47 compliant language identifer tag
	 */
	protected _getLanguageIdentifierTag(): Promise<string> {
		if (!this._platform.is('cordova')) {
			return Promise.resolve(window.navigator['userLanguage'] || window.navigator['language'] || 'da-DK');
		}
		return this._globalization
			.getLocaleName()
			.then(data => data.value);
	}

}

```

If I remove Globalization from constructor and comment out associated code it complains with the same error but a different plugin.

Did I miss something?

EDIT: It just hit me, I need to add it to NgModule's provider array, right?
EDIT 2: That was it :)

**Comment by crscaballero** [comment]
Thanks so much, i have the same problem
