### ISSUE TITLE
Super template not compatible with ionic-native 3+

### ISSUE THREAD

**Issue by 05bca054** [driftyco/ionic-native#1253]
Hello,

I have tried many times to work with ionic but i think super template from ionic is not quite working with ionic-naitve V3+.

Yet i tried to fix several errors(Which causes ionic-native to run) but now i stuck with weird error(No modification made to template pages) which says

Runtime Error
Error in :0:0 caused by: No provider for SplashScreen!

Error: DI Error
    at v (http://localhost:8100/build/polyfills.js:3:4864)
    at NoProviderError.BaseError [as constructor] (http://localhost:8100/build/main.js:35764:27)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8100/build/main.js:76992:16)
    at new NoProviderError (http://localhost:8100/build/main.js:77054:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:112940:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:112979:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:112911:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/main.js:112780:21)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:77928:52)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:8100/build/main.js:113715:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:8100/build/main.js:114143:49)
    at ElementInjector.get (http://localhost:8100/build/main.js:113219:27)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:8100/build/main.js:113715:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:8100/build/main.js:114143:49)
    at CompiledTemplate.proxyViewClass.View_MyApp_Host0.createInternal (/AppModule/MyApp/host.ngfactory.js:15:255)

-Naitik

**Comment by ihadeed** [comment]
Did you add `SplashScreen` and other plugin providers to your `@NgModule` ?

**Comment by 05bca054** [comment]
Thank you ihadeed,

This will fix those problem, but i recommended that update super template which fix those ionic-native V3+ issues.

-Naitik

**Comment by ihadeed** [comment]
This issue was moved to driftyco/ionic-starter-super#86
