### ISSUE TITLE
build --prod --aot gives error

### ISSUE THREAD

**Issue by Langstra** [driftyco/ionic-native#1384]
In my providers array I use the following to override the default behavior for the file-transfer-plugin.
```
{provide: FileOpener, useFactory: (platform: Platform) => {return new FileOpenerProvider(platform)}, deps: [Platform]}
```
I am sure this is the problem. When commenting out this line in app.module.ts the build works.
So when running `ionic cordova build --prod --aot` I get the following error.
```
{ Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 121:43 in the original .ts file), resolving symbol AppModule in /opt/projects/ionic_project/taxatie/src/app/app.module.ts
    at positionalError (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:23471:35)
    at simplifyInContext (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:23314:27)
    at StaticReflector.simplify (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:23328:13)
    at StaticReflector.annotations (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:22794:60)
    at NgModuleResolver.resolve (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:13352:70)
    at CompileMetadataResolver.getNgModuleMetadata (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:13937:60)
    at addNgModule (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:22526:58)
    at /opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:22537:14
    at Array.forEach (native)
    at _createNgModules (/opt/projects/ionic_project/taxatie/node_modules/@angular/compiler/bundles/compiler.umd.js:22536:26) hasBeenLogged: undefined, isFatal: undefined, name: 'Error' }
```
Is there a solution known for this problem? Or any other way that you should override behavior?

**Comment by rapropos** [comment]
In the future, please use [the support forums](https://forum.ionicframework.com/) for support requests like this. [angular #11262](https://github.com/angular/angular/issues/11262) explains the issue.

**Comment by Langstra** [comment]
Thanks, sorry for the inconvenience.
