### ISSUE TITLE
can't resolve module @ionic-native/core from @ionic-native/in-app-browser/index.d.ts

### ISSUE THREAD

**Issue by praveenyoungind** [driftyco/ionic-native#1395]
> **ionic build android --prod --release fails with the below error**
> **ionic build android --release is working fine**

# can't resolve module @ionic-native/core from /MyProject/node_modules/@ionic-native/in-app-browser/index.d.ts
`
[10:20:09] build prod failed: Cannot read property 'Plugin' of undefined, resolving symbol InAppBrowser in /MyProject/node_modules/@ionic-native/in-app-browser/index.d.ts 
[10:20:09] ionic-app-script task: "build" 
[10:20:09] Error: Cannot read property 'Plugin' of undefined, resolving symbol InAppBrowser in /MyProject/node_modules/@ionic-native/in-app-browser/index.d.ts Error: Cannot read property 'Plugin' of undefined, resolving symbol InAppBrowser in /MyProject/node_modules/@ionic-native/in-app-browser/index.d.ts at simplifyInContext (/MyProject/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23) at StaticReflector.simplify (/MyProject/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22) at StaticReflector.annotations (/MyProject/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36) at NgModuleResolver.resolve (/MyProject/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46) at CompileMetadataResolver._loadNgModuleMetadata (/MyProject/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45) at CompileMetadataResolver.getUnloadedNgModuleMetadata (/MyProject/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23) at addNgModule (/MyProject/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43) at /MyProject/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16 at Array.forEach (native) at _createNgModules (/MyProject/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
`

My package.json

```
**`
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic-native/core": "^3.4.4",
    "@ionic-native/in-app-browser": "^3.4.4",
    "@ionic-native/onesignal": "^3.4.4",
    "@ionic/storage": "2.0.1",
    "angular2-moment": "1.3.3",
    "font-awesome": "^4.7.0",
    "ionic-angular": "2.1.0",
    "ionic-native": "2.4.1",
    "ionic2-autosize": "1.0.2",
    "ionicons": "3.0.0",
    "moment": "^2.18.1",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.3",
    "typescript": "2.0.9"
  },**
```
`

**Comment by rapropos** [comment]
It looks to me like you have two conflicting versions of ionic-native installed. I would get rid of the "ionic-native" one. Also, since ionic-native 3 has Angular 4 as a dev dependency, I would look at upgrading that as well.

**Comment by praveenyoungind** [comment]
what is the solution to fix this error can u guide

**Comment by rapropos** [comment]
This is not a good candidate for a GitHub issue. Please open a topic on [the support forums](https://forum.ionicframework.com) instead.

**Comment by praveenyoungind** [comment]
done https://forum.ionicframework.com/t/cant-resolve-module-ionic-native-core-from-ionic-native-in-app-browser-index-d-ts-1395/87428

**Comment by JiahaoShan** [comment]
I had the same issue.
