### ISSUE TITLE
Can't build for Android in --prod with @ionic-native/diagnostic

### ISSUE THREAD

**Issue by dwm-it** [driftyco/ionic-native#1402]
Hello,

I added the diagnostic plugin to my Ionic 2 project : 
`ionic plugin add cordova.plugins.diagnostic --save`
`npm install --save @ionic-native/diagnostic`

Since this, i can build in debug mode (ionic build android) but not in --prod mode (ionic build android --prod).

Here is the log : 

```
[14:30:11]  ionic-app-scripts 1.0.0
[14:30:11]  build prod started ...
[14:30:11]  clean started ...
[14:30:11]  clean finished in 1 ms
[14:30:11]  copy started ...
[14:30:11]  ngc started ...
can't resolve module @ionic-native/core from /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
[14:30:13]  build prod failed: Cannot read property 'Plugin' of undefined, resolving symbol Diagnostic in
            /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
[14:30:13]  ionic-app-script task: "build"
[14:30:13]  Error: Cannot read property 'Plugin' of undefined, resolving symbol Diagnostic in
            /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
Error: Cannot read property 'Plugin' of undefined, resolving symbol Diagnostic in /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@ionic-native/diagnostic/index.d.ts
    at simplifyInContext (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/florianpetit/Documents/DWM/Projets/Enedis/Cod'Here/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
```

Here is my 'package.json' : 
```
{
  "name": "app-name",
  "author": "Me",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic-native/core": "^3.5.0",
    "@ionic-native/diagnostic": "^3.5.0",
    "@ionic/storage": "1.1.7",
    "@types/google-maps": "^3.2.0",
    "angular2-jwt": "^0.1.28",
    "ionic-angular": "2.0.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "moment": "^2.18.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "description": "An Ionic project"
}
```

ionic info :
```
Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1
ios-sim version: 3.1.1
OS: macOS Sierra
Node Version: v7.8.0
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

Any idea ?

**Comment by dwm-it** [comment]
Still the same error ! 
Nobody has any idea ?

**Comment by danielsogl** [comment]
Hey @dwm-it,

you should definitely upgrade to Ionic Native 3! I tried to reproduce your issue with Ionic Native 3 and can tell you, you won't have a problem with it.

Run `npm uninstall --save ionic-native` first and then run `npm install --save @ionic-native/core`

Read [this blog post](http://blog.ionic.io/ionic-native-3-x/) to learn more about Ionic Native 3.

**Comment by ihadeed** [comment]
@dwm-it is this still an issue with ionic native 3.7.0 ?
