### ISSUE TITLE
How to properly use ionic-native on ionic serve?

### ISSUE THREAD

**Issue by JPeColCom** [driftyco/ionic-native#265]
Am I doing here what's wrong?
I get via ionic serve in the browser the following exception:

```
browser_adapter.js:77 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No provider for TouchID!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:8100/build/js/app.bundle.js:1815:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8100/build/js/app.bundle.js:27006:16)
    at new NoProviderError (http://localhost:8100/build/js/app.bundle.js:27043:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/js/app.bundle.js:28031:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/js/app.bundle.js:28059:25)
    at ReflectiveInjector_._getByKey (http://localhost:8100/build/js/app.bundle.js:28022:25)
    at ReflectiveInjector_.get (http://localhost:8100/build/js/app.bundle.js:27831:21)
    at ElementInjector.get (http://localhost:8100/build/js/app.bundle.js:29405:48)
    at ElementInjector.get (http://localhost:8100/build/js/app.bundle.js:29405:48)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/js/app.bundle.js:28056:24)
ERROR CONTEXT:
[object Object]
```

What im doing:

```
import {Component} from '@angular/core';
import {Platform} from 'ionic-angular';
import {TouchID} from 'ionic-native';
import {AboutPage} from '../about/about';

@Component({
  templateUrl: 'build/pages/settings/settings.html'
})
export class SettingsPage {
    aboutPage = AboutPage;
    touchIDAvailable: boolean;

  constructor(platform: Platform, touchID: TouchID) {
    this.touchIDAvailable = false;

    platform.ready().then(() => {
      touchID.isAvailable().then(
        res => this.touchIDAvailable = true,
        err => this.touchIDAvailable = false
      )
    })
  }
}
```

**Comment by lthh89vt** [comment]
Try to remove touchId: TouchID in your constructor

Ionic Native allows you interact directly with Android so it's not part of angular2 => don't need to declare it.

then you can use static method like TouchId.isAvailable() or TouchID.verifyFingerprint() in platform.ready().

Hope it helps!

**Comment by JPeColCom** [comment]
Thanks! This way works 👍 
```
import {Component} from '@angular/core';
import {Platform} from 'ionic-angular';
import {TouchID} from 'ionic-native';
import {AboutPage} from '../about/about';


@Component({
  templateUrl: 'build/pages/settings/settings.html'
})
export class SettingsPage {
    aboutPage: any = AboutPage;
    touchID: any = TouchID;
    touchIDAvailable: boolean = false;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      this.touchID.isAvailable().then(
        res => this.touchIDAvailable = true,
        err => this.touchIDAvailable = false
      )
    })
  }
}

```

**Comment by lthh89vt** [comment]
No worries. I'm new to Ionic 2, too so very glad that I can help.

Just a quick note (and please correct me if I'm wrong)
You won't need to specify those variable in your component. Something like this will do.

```
import {Component} from '@angular/core';
import {Platform} from 'ionic-angular';
import {TouchID} from 'ionic-native';
import {AboutPage} from '../about/about';


@Component({
  templateUrl: 'build/pages/settings/settings.html'
})
export class SettingsPage {

  touchIDAvailable: boolean = false;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      TouchID.isAvailable().then(
        res => this.touchIDAvailable = true,
        err => this.touchIDAvailable = false
      )
    })
  }
}
```

And about page can be called like `navController.push(AboutPage)`
Need to add navController to constructor.

**Comment by JPeColCom** [comment]
Yeah, but TouchID.isAvailable() isn't a static Method, and end's in an compile error.

The About Page will push via html directive
```
<ion-item-group>
  <ion-item-divider light>Info</ion-item-divider>
  <button ion-item [navPush]="aboutPage">About</button>
</ion-item-group>
```

**Comment by lthh89vt** [comment]
Very interesting! 

Thanks for the head ups.
