### ISSUE TITLE
googlemaps.addGroundOverlay

### ISSUE THREAD

**Issue by Kayrohinc** [driftyco/ionic-native#383]
Hello! I try to add GroundOverlay using  https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/GroundOverlay  as example

```
   GoogleMap.isAvailable().then(() => {
this.map.one(GoogleMapsEvent.MAP_READY).then((data)=>{console.log("t"+data);
		let myPosition = new GoogleMapsLatLng("64.8", "24.8");  
    let bounds= [new GoogleMapsLatLng("59.8", "19.3"), new GoogleMapsLatLng("69.0", "31.2") ];
    this.map.setZoom(5);
//let groundoptions: GoogleMapsGroundOverlayOptions;
 // groundoptions.bounds=bounds;
 // groundoptions.url="http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg";
   this.map.addGroundOverlay({
  'url': "http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg",
  'bounds': bounds,
  'opacity': 0.5
}).then((groundOverlay)=> {
 this.map.showDialog();
 this.map.animateCamera({
    'target': bounds
  });
});
```

but I catch exeption -

```
I/chromium(22130): [INFO:CONSOLE(63)] "t[object Object]", source: file:///android_asset/www/build/js/app.bundle.js (63)
W/Google Maps Android API(22130): GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API(22130): GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API(22130): GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API(22130): GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API(22130): GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API(22130): GLHudOverlay deprecated; getDrawOrder(): no-op, return DrawOrder.HEADS_UP_DISPLAY
W/Google Maps Android API(22130): GLHudOverlay deprecated; draw(): no-op
W/Google Maps Android API(22130): GLHudOverlay deprecated; draw(): no-op
I/chromium(22130): [INFO:CONSOLE(33686)] "EXCEPTION: Error: Uncaught (in promise): Error: tilelayerOptions.tileUrlFormat should set a string.", source: file:///android_asset/www/build/js/app.bundle.js (33686)
I/chromium(22130): [INFO:CONSOLE(33686)] "STACKTRACE:", source: file:///android_asset/www/build/js/app.bundle.js (33686)
I/chromium(22130): [INFO:CONSOLE(33686)] "Error: Uncaught (in promise): Error: tilelayerOptions.tileUrlFormat should set a string.
I/chromium(22130):     at resolvePromise (file:///android_asset/www/build/js/zone.js:538:32)
I/chromium(22130):     at resolvePromise (file:///android_asset/www/build/js/zone.js:523:18)
I/chromium(22130):     at file:///android_asset/www/build/js/zone.js:571:18
I/chromium(22130):     at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/zone.js:356:38)
I/chromium(22130):     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (file:///android_asset/www/build/js/app.bundle.js:30485:41)
I/chromium(22130):     at ZoneDelegate.invokeTask (file:///android_asset/www/build/js/zone.js:355:43)
I/chromium(22130):     at Zone.runTask (file:///android_asset/www/build/js/zone.js:256:48)
I/chromium(22130):     at drainMicroTaskQueue (file:///android_asset/www/build/js/zone.js:474:36)
I/chromium(22130):     at ZoneTask.invoke (file:///android_asset/www/build/js/zone.js:426:22)", source: file:///android_asset/www/build/js/app.bundle.js (33686)
I/chromium(22130): [INFO:CONSOLE(461)] "Unhandled Promise rejection:", source: file:///android_asset/www/build/js/zone.js (461)
I/chromium(22130): [INFO:CONSOLE(463)] "Error: Uncaught (in promise): Error: tilelayerOptions.tileUrlFormat should set a string.", source: file:///android_asset/www/build/js/zone.js (463)
```

what's wrong? Is it a bug or no?

**Comment by Kayrohinc** [comment]
Help, pls..

**Comment by ihadeed** [comment]
Hey there

Just had a quick look at the stack trace here on my phone.

I doubt that this is an ionic native issue, but we can keep this open till
we confirm that.

Looking at your stack trace I think the problem is here

"Error: Uncaught (in promise): Error: tilelayerOptions.tileUrlFormat should
set a string."

You might be missing the tileUrlFormat somewhere in the options for the
tileLayer

**Comment by Kayrohinc** [comment]
Hello! I find how  to fix this bug. 
in googlemaps.js  file  you need to change  line 184             

`_this._objectInstance.addTileOverlay(options, function (groundOverlay) {
`
to  
`   _this._objectInstance.addGroundOverlay(options, function (groundOverlay) {`
also, the same bug in line  195: 
`            _this._objectInstance.addTileOverlay(options, function (kmlOverlay) {
`
change to ` this._objectInstance.addKmlOverlay(options, function (kmlOverlay) {`

old 
![image](https://cloud.githubusercontent.com/assets/5566123/17457455/8c39133c-5c01-11e6-98cf-0e114159102f.png)

new 
![image](https://cloud.githubusercontent.com/assets/5566123/17457458/aa7c7230-5c01-11e6-84ee-ed839b3ca3d4.png)

**Comment by kessiler** [comment]
This issue is already fixed.
Upgrade **ionic-native** to **v1.3.10**

**Comment by Kayrohinc** [comment]
Thx!
