### ISSUE TITLE
Problem generate docs 

### ISSUE THREAD

**Issue by ramonornela** [driftyco/ionic-native#629]
See [CircleCI](https://circleci.com/gh/driftyco/ionic-native/1085#build-timing/containers/0)
```
./scripts/docs/update_docs.sh

##### 
##### ci/deploy.sh
#####
[20:59:36] Using gulpfile ~/ionic-native/gulpfile.js
[20:59:36] Starting 'docs'...
error:   Error: Only one of "private" (or its aliases) allowed. There were 2 - doc "src/index/PayPalConfiguration" (interface)  - from file "/home/ubuntu/ionic-native/src/plugins/pay-pal.ts"
    at readTags (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:127:15)
    at /home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:86:11
    at Function.forEach (/home/ubuntu/ionic-native/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:3298:15)
    at tagExtractor (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:65:9)
    at /home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:20:9
    at Array.forEach (native)
    at Object.$process (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:18:12)
    at /home/ubuntu/ionic-native/node_modules/dgeni/lib/Dgeni.js:202:28
    at _fulfilled (/home/ubuntu/ionic-native/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/ubuntu/ionic-native/node_modules/q/q.js:863:30)
error:   Error processing docs:  Error: Only one of "private" (or its aliases) allowed. There were 2 - doc "src/index/PayPalConfiguration" (interface)  - from file "/home/ubuntu/ionic-native/src/plugins/pay-pal.ts"
    at readTags (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:127:15)
    at /home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:86:11
    at Function.forEach (/home/ubuntu/ionic-native/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:3298:15)
    at tagExtractor (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:65:9)
    at /home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:20:9
    at Array.forEach (native)
    at Object.$process (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:18:12)
    at /home/ubuntu/ionic-native/node_modules/dgeni/lib/Dgeni.js:202:28
    at _fulfilled (/home/ubuntu/ionic-native/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/ubuntu/ionic-native/node_modules/q/q.js:863:30)
[20:59:40] 'docs' errored after 3.63 s
[20:59:40] Error: Only one of "private" (or its aliases) allowed. There were 2 - doc "src/index/PayPalConfiguration" (interface)  - from file "/home/ubuntu/ionic-native/src/plugins/pay-pal.ts"
    at readTags (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:127:15)
    at /home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:86:11
    at Function.forEach (/home/ubuntu/ionic-native/node_modules/dgeni-packages/node_modules/lodash/dist/lodash.js:3298:15)
    at tagExtractor (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:65:9)
    at /home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:20:9
    at Array.forEach (native)
    at Object.$process (/home/ubuntu/ionic-native/node_modules/dgeni-packages/jsdoc/processors/extract-tags.js:18:12)
    at /home/ubuntu/ionic-native/node_modules/dgeni/lib/Dgeni.js:202:28
    at _fulfilled (/home/ubuntu/ionic-native/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/ubuntu/ionic-native/node_modules/q/q.js:863:30)

./scripts/docs/update_docs.sh returned exit code 1

Action failed: ./scripts/docs/update_docs.sh
```

**Comment by perrygovier** [comment]
`@private` tags are not needed on the interface if the var is marked private.

**Comment by perrygovier** [comment]
fixed in 973c80b26484bb6884fb9334f931667daadf6212

**Comment by ramonornela** [comment]
Thanks 😉

**Comment by ihadeed** [comment]
thanks @perrygovier !
