### ISSUE TITLE
Ionic2 app does not build using camera plugin

### ISSUE THREAD

**Issue by rocco** [driftyco/ionic-native#631]
I am using ionic-native's master branch (same issue for v2.1.0). My Ionic2 (also v2.1.0) app uses the camera plugin like this:
```
import { Component } from '@angular/core';
import { Camera } from 'ionic-native';

@Component({
  templateUrl: 'start.html'
})
export class StartPage {
  cameraImage: string;

  constructor () {
  }

  takePicture () {
    Camera.getPicture({}).then((imageData) => {
     this.cameraImage = imageData;
    }, (err) => {
     // Handle error
    });
  }
}
```

... not much going on here, just the import of Camera and a call to Camera.getPicture().

I am getting an error when trying to build the app:

```
$ ionic build ios

Running 'build:before' npm script before build
> ionic-hello-world@ build /Users/_somepath_
> ionic-app-scripts build
[13:58:52]  ionic-app-scripts 0.0.23
[13:58:52]  build prod started ...
[13:58:52]  clean started ...
[13:58:52]  clean finished in 24 ms
[13:58:52]  copy started ...
[13:58:52]  ngc started ...
[13:58:52]  lint started ...
[13:58:52]  copy finished in 189 ms
[13:58:53]  lint finished in 1.28 s
[13:59:16]  ngc finished in 23.77 s
[13:59:16]  bundle prod started ...
[13:59:26]  Error: Module /Users/_somepath_/node_modules/ionic-native/dist/index.js does not export Camera (imported by /Users/_somepath_/.tmp/pages/start/start.js)
    at Module.trace (/Users/_somepath_/node_modules/rollup/dist/rollup.js:7677:29)
    at ModuleScope.findDeclaration (/Users/_somepath_/node_modules/rollup/dist/rollup.js:7300:22)
    at Scope.findDeclaration (/Users/_somepath_/node_modules/rollup/dist/rollup.js:5351:39)
    at Scope.findDeclaration (/Users/_somepath_/node_modules/rollup/dist/rollup.js:5351:39)
    at MemberExpression.bind (/Users/_somepath_/node_modules/rollup/dist/rollup.js:6666:28)
    at /Users/_somepath_/node_modules/rollup/dist/rollup.js:5151:50
    at CallExpression.eachChild (/Users/_somepath_/node_modules/rollup/dist/rollup.js:5168:5)
    at CallExpression.bind (/Users/_somepath_/node_modules/rollup/dist/rollup.js:5151:7)
    at CallExpression.bind (/Users/_somepath_/node_modules/rollup/dist/rollup.js:5842:23)
    at /Users/_somepath_/node_modules/rollup/dist/rollup.js:5151:50
```

This is related to commit 9bffc994e7ddf9b4a0e3001ec8ecd6f17f947374 where the `Camera` object, amongst others, was removed from the export object in index.ts, thus causing it to be missing from dist/index.js as complained about in the error message above (also see my comments on the commit's page).

Since this has been committed quite a while ago (June 11) I am wondering if I am the only one to come across this error or if maybe something else in the Ionic2 build chain has changed since then causing this to happen. However if you put Camera back into the export object in index.ts and rebuild to dist/index.js all works as it should - as I said, many other plugins seem to be affected, I just tested Camera.

**Comment by mlynch** [comment]
Master is broken. 2.0.3 is the only working version currently, and we're aware of the above and working on it, thanks.
