### ISSUE TITLE
Image Picker: hasReadPermission and requestReadPermission methods do not work

### ISSUE THREAD

**Issue by pdrosos** [driftyco/ionic-native#788]
Hi,

I am using the [Image picker](http://ionicframework.com/docs/v2/native/image-picker/) plugin.
It seems that the hasReadPermission and requestReadPermission methods do not exist in the plugin, because when I try to use them, I have this error:
```
8     424399   error    EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
9     424401   error    ORIGINAL STACKTRACE:
10    424403   error    Error: Uncaught (in promise): TypeError: Cannot read property 'apply' of undefined
    at s (http://192.168.1.146:8100/build/polyfills.js:3:8568)
    at s (http://192.168.1.146:8100/build/polyfills.js:3:8391)
    at http://192.168.1.146:8100/build/polyfills.js:3:8902
    at t.invokeTask (http://192.168.1.146:8100/build/polyfills.js:3:14051)
    at Object.onInvokeTask (http://192.168.1.146:8100/build/main.js:4:20334)
    at t.invokeTask (http://192.168.1.146:8100/build/polyfills.js:3:13987)
    at e.runTask (http://192.168.1.146:8100/build/polyfills.js:3:11411)
    at i (http://192.168.1.146:8100/build/polyfills.js:3:8028)
    at HTMLButtonElement.invoke (http://192.168.1.146:8100/build/polyfills.js:3:15204)
11    424408   error    Unhandled Promise rejection:, Cannot read property 'apply' of undefined, ; Zone:, angular, ; Task:, Promise.then, ; Value:, [object Object], TypeError: Cannot read property 'apply' of undefined
    at r (http://192.168.1.146:8100/build/main.js:2:24058)
    at http://192.168.1.146:8100/build/main.js:2:24970
    at http://192.168.1.146:8100/build/main.js:2:24256
    at new t (http://192.168.1.146:8100/build/polyfills.js:3:15636)
    at e (http://192.168.1.146:8100/build/main.js:2:24230)
    at s (http://192.168.1.146:8100/build/main.js:2:24899)
    at o (http://192.168.1.146:8100/build/main.js:2:24952)
    at Function.<anonymous> (http://192.168.1.146:8100/build/main.js:2:28977)
    at Function.value [as hasReadPermission] (http://192.168.1.146:8100/build/main.js:2:27212)
    at Object.handler (http://192.168.1.146:8100/build/main.js:8:10922)
```

**Comment by ihadeed** [comment]
Do you have the plugin installed? Are you running on a device/simulator? Does the `getPictures` method work?

**Comment by royipressburger** [comment]
@pdrosos @ihadeed From what I know this is a bug with the plugin itself.. Take a look here https://github.com/wymsee/cordova-imagePicker/pull/136
There is a waiting pullrequest for some time now :\

**Comment by ihadeed** [comment]
Sometimes we get the error `Cannot read property 'apply' of undefined` if our `callCordovaPlugin` (plugin.ts line 104) is unable to find the method we are referring to (for many reasons).

**Comment by pdrosos** [comment]
@ihadeed I switched to Camera plugin, which works better for selecting single image, which was what I needed. When I tried this plugin, it was installed and I tested on real device with Android 6.0.
Method getPictures worked for selecting one image, only these two methods didn't.

**Comment by ihadeed** [comment]
Oh yeah, sorry.

This is the correct repo for the wrapper we are using: https://github.com/Telerik-Verified-Plugins/ImagePicker

I updated it recently but forgot to change the repo url.

**Comment by ihadeed** [comment]
Updated it, should be fixed in the next docs update.
