### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic-native#948]
I am trying to contribute code for a Cordova plugin, but I'm unable to build ionic native using `npm run build`, event without having modified any code.

```
bash-3.2$ npm run build

> ionic-native@2.2.14 build /Users/kim/ionic/contribute/ionic-native
> npm run lint && npm run build:js && npm run build:esm && npm run build:bundle && npm run build:minify


> ionic-native@2.2.14 lint /Users/kim/ionic/contribute/ionic-native
> gulp lint

[11:45:13] Using gulpfile ~/ionic/contribute/ionic-native/gulpfile.js
[11:45:13] Starting 'lint'...
[11:45:13] Finished 'lint' after 11 ms

> ionic-native@2.2.14 build:js /Users/kim/ionic/contribute/ionic-native
> tsc -p tsconfig-es5.json

src/plugins/contacts.ts(84,7): error TS2536: Type 'keyof this' cannot be used to index type 'Contact'.

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:js"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! ionic-native@2.2.14 build:js: `tsc -p tsconfig-es5.json`
npm ERR! Exit status 2
```

I'm using Node v6.9.1

Is master branch currently broken?

**Comment by ihadeed** [comment]
The tslint is failing, there is an issue at line 84 of contacts.ts. Pull latest version of the repo, seems like it's building fine according to CircleCI.

**Comment by biesbjerg** [comment]
It doesn't look like the lint is failing to me. It's the typescript compilation:

```
> tsc -p tsconfig-es5.json

src/plugins/contacts.ts(84,7): error TS2536: Type 'keyof this' cannot be used to index type 'Contact'.
```

It happens on a 100% fresh `git clone` from driftyco/ionic-native repo for me.

**Comment by ihadeed** [comment]
@biesbjerg works fine with me. Running node 7.3.x and Typescript 2.0.10.

**Comment by biesbjerg** [comment]
Hmm seems the installed typescript version is 2.1.4 because of the caret in package.json:

```
...
"typescript": "^2.0.1",
...
```

Which resolves to latest version in the 2.x.x range.

Did you do a clean `git clone`, `npm install`and then `npm run build` when testing?

**Comment by ihadeed** [comment]
@biesbjerg no, i'll try that in a bit.

**Comment by ihadeed** [comment]
thanks for pointing this out @biesbjerg just fixed it!

**Comment by zbicin** [comment]
@ihadeed unfortunately it seems that the issue is back. The `npm install` installs now TypeScript 2.2.1, as it is explicitly stated in ionic-native's `package.json`: 

```
    "typescript": "2.2.1",
```

Unfortunately installing `TypeScript@2.0.10`, as @biesbjerg suggested before, doesn't help much, because it produces another set of errors.

I've cut some of the output to keep it more clear:

```
$ git clone git@github.com:driftyco/ionic-native.git && cd ionic-native && npm i && npm run build
(...)

> ionic-native@3.6.1 build D:\ionic-native
> npm run clean && npm run lint && npm run build:core && npm run build:modules


> ionic-native@3.6.1 clean D:\ionic-native
> rimraf dist .tmp


> ionic-native@3.6.1 lint D:\ionic-native
> gulp lint
(...)

> ionic-native@3.6.1 build:core D:\ionic-native
> ngc -p scripts/build/tsconfig-core.json


> ionic-native@3.6.1 build:modules D:\ionic-native
> node scripts/build/build.js

Making new TMP directory
Preparing core module package.json
Building plugin: action-sheet
(...)
Building plugin: device
Error building plugins.

Building contacts failed.
{ Error: Command failed: D:\ionic-native/node_modules/.bin/ngc -p D:\ionic-native\.tmp\plugins\contacts\tsconfig.json
Error at D:/ionic-native/src/@ionic-native/plugins/contacts/index.ts:85:7: Type 'keyof this' cannot be used to index type 'Contact'.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\ionic-native/node_modules/.bin/ngc -p D:\\ionic-native\\.tmp\\plugins\\contacts\\tsconfig.json' }
```

**Comment by jlahare** [comment]
Is there any update over this issue ? as this issue is not completely resolved !!!
